version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=postgres user=postgres password=word_pass dbname=postgres sslmode=disable"
    ports:
      - "3002:3002"  
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: word_pass
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}
